// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {Promise<boolean> & { cancel(): void }}
 */
export function Arm() {
    let $resultPromise = /** @type {any} */($Call.ByID(1487033878));
    return $resultPromise;
}

/**
 * @param {string} command
 * @param {$models.Config | null} config
 * @returns {Promise<$models.ExecResult> & { cancel(): void }}
 */
export function ExecCommand(command, config) {
    let $resultPromise = /** @type {any} */($Call.ByID(1086165234, command, config));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.ExecResult.createFrom;
